TestIdeas/TestIdeas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestIdeas.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TestIdeas/TestIdeas/Controllers/ParameterValidationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using TestIdeas.Models;

namespace TestIdeas.Controllers
{
    public class ParameterValidationController : Controller
    {
        // GET: ParameterValidation
        public ActionResult ParameterValidationTest()
        {
            var internalUnit = UnitBuilder.GetUnit("m");
            var displayUnit = UnitBuilder.GetUnit("cm");

            var model = new Quantity
            {
                Name = "Length",
                InternalUnit = internalUnit,
                DisplayUnit = displayUnit,
                InternalMin = 5,
                InternalMax = 10
            };

            return View(model);
        }
    }
}

TestIdeas/TestIdeas/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TestIdeas/TestIdeas/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestIdeas/TestIdeas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="well">
    <h1>Simple Web</h1>
    <p class="lead">A place for testing ideas.</p>
</div>

<div class="row">
    <div class="col-md-4 rounded-border-box">
        <a href="@Url.Action("GasProperties", "GasProperties")">
            <img src="..\Images\Conversion.png" alt="Test 1" style="width:80px; height:80px" />
            <h3>Test Calculation 1</h3>
        </a>
        <p>Bla bla bla bla bla bla bla bla bla bla bla bla. This long description should be shortened...</p>
    </div>
    <div class="col-md-4 rounded-border-box">
        <a href="@Url.Action("ParameterValidationTest", "ParameterValidation")">
            <img src="..\Images\drop.png" alt="Test 2" style="width:80px; height:80px" />
            <h3>Test Calculation 2</h3>
        </a>
        <p>Bla bla bla bla bla bla bla bla bla bla bla bla. This long description should be shortened...</p>
    </div>
</div>